name: person

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: any
  cl:
    git: git@repo.centryl.org:centryl/cl.git
  cl_base:
    git: git@repo.centryl.org:centryl/cl_base.git

dev_dependencies:
  build_runner: ^2.1.11
  build_web_compilers: ^3.2.3
